Localisation_App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


app_name = 'Localisation_App'
urlpatterns = [
     path('', views.Home, name='Home'),
     path('aboutus/', views.aboutus, name='aboutus'),
     path('toolsPage/', views.toolsPage, name='toolsPage'),
     path('tools/', views.tools, name='tools'),
     path('toolsDownloadCounter/<int:id>',
          views.toolsDownloadCounter, name='toolsDownloadCounter'),
     path('toolsReset/', views.toolsReset, name='toolsReset'),
     path('toolsSearch/<tools_title>', views.toolsSearch, name='toolsSearch'),
     path('resourcesPage/', views.resourcesPage, name='resourcesPage'),
     path('resources/', views.resources, name='resources'),
     path('resourceDownloadCounter/<int:id>',
          views.resourceDownloadCounter, name='resourceDownloadCounter'),
     path('resourcesReset/', views.resourcesReset, name='resourcesReset'),
     path('resourceSearch/<slug:resource_title>',
          views.resourceSearch, name='resourceSearch'),
     path('services/', views.services, name='services'),
     path('successstoryPage/', views.successstoryPage, name='successstoryPage'),
     path('successstory/', views.successstory, name='successstory'),
     path('successstorySearch/<story_title>',
          views.successstorySearch, name='successstorySearch'),
     #     path('successstoryReset/', views.successstoryReset, name='successstoryReset'),
     path('submit/', views.submit, name='submit'),
     path('faqs/', views.faqs, name='faqs'),
     path('faqsSearch/<faq_title>', views.faqsSearch, name='faqsSearch'),
     path('contactus/', views.contactus, name='contactus'),
     path('websitepolicy/', views.websitepolicy, name='websitepolicies'),
     path('websitepolicy/<int:id>', views.websitepolicydata,
          name='websitepolicydata'),
     path('termsandcondition/', views.termsandcondition, name='termsandcondition'),
     path('accessibilityStatement/', views.accessibilityStatement,
          name='accessibilityStatement'),
     path('sitemap/', views.sitemap, name='sitemap'),
     path('help/', views.help, name='help'),
     path('submit/<img>', views.submit, name='submit'),
     path('help/<int:id>', views.helpData, name='helpData'),
     path('srvEnableTyping/', views.srvEnableTyping, name='srvEnableTyping'),
     path('srvGoTranslateWebLocalizer/', views.srvGoTranslateWebLocalizer,
          name='srvGoTranslateWebLocalizer'),
     path('srvOnscreenKeyboard/', views.srvOnscreenKeyboard,
          name='srvOnscreenKeyboard'),
     path('srvTTS/', views.srvTTS, name='srvTTS'),
     path('srvTransliteration/', views.srvTransliteration,
          name='srvTransliteration'),
     path('register/', views.Register_user, name="register"),
     path('login/', views.login_user, name='login'),
     path('logout/', views.logout_user, name='logout'),
     path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
     path('changePassword/<token>/', views.changePassword, name='changePassword'),
     path('profile/<int:id>', views.User_Profile, name="profile"),

     path('goTranslate/', views.goTranslate,
          name='goTranslate'),
     path('translation-quote/', views.translation_quote,
          name='translation_quote'),
     path('translation-quote-user-dashboard', views.translation_quote_user_dashboard,
          name='translation_quote_user_dashboard'),
     path('translation-quote-show/<str:application_number>/',
          views.translation_quote_show, name='translation_quote_show'),
     #     path('dashboard2', views.dashboard2, name="dashboard2"),
     path('dashboard', views.dashboard, name="dashboard"),
     path('machine-translation/', views.machine_translation,
          name="machine_translation"),
     path('name-matcher/', views.name_matcher, name="name_matcher"),
     path('empanelled_agencies/', views.empanelled_agencies,
          name="empanelled_agencies"),
     path('bhashini/',views.bhashini,name="bhashini"),
     path('anuvaad/',views.anuvaad, name="anuvaad")

     #     path("Slug_test/<slug:slug>", views.Slug_test, name="Slug_test"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

Localisation_Project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Localisation_App.urls'))

]

Localisation_App/views.py
from threading import currentThread
from wsgiref import validate
from django.db.models import Sum
from django.forms import ValidationError
from Localisation_Project.settings import CACHE_TTL
from .forms import TTSservice, RegisterForm, TranslationQuoteForm, UserLoginForm, UserChangePasswordForm, UserForgetPasswordForm
from django.contrib import messages
from django.core.mail import send_mail, mail_admins
from django.core.paginator import Paginator
from multiprocessing import context
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from .models import *
import random
import requests
from .word_count import crawl_data
from django.contrib.auth.models import User
import uuid
from datetime import date, datetime
from .helpers import send_forget_password_email
import json
from bson import json_util
from django.urls import resolve
import uuid
from django.contrib.auth.decorators import login_required
import logging
from datetime import date
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.core import validators
logger = logging.getLogger('django')
global str_num
global url
CACHE_TTL = getattr(settings,'CACHE_TTL',DEFAULT_TIMEOUT)


# Home Page

def Home(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("url", url)
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_Article_data"):
            articleData = cache.get("All_Article_data")
            print("cache data")
        else:
            articleData = Article.objects.all()
            cache.set("All_Article_data", articleData)
            print("database data")

        if cache.get("All_SuccessStories_data"):
            successStoriesData = cache.get("All_SuccessStories_data")
            print("cache data")
        else:
            successStoriesData = SuccessStories.objects.all()
            cache.set("All_SuccessStories_data", successStoriesData)
            print("database data")

        if cache.get("All_Services_data"):
            servicesdata = cache.get("All_Services_data")
            print("cache data")
        else:
            servicesdata = Services.objects.all()
            cache.set("All_Services_data", servicesdata)
            print("database data")

        if cache.get("All_NewsAndEvents_data"):
            newsAndEventsData = cache.get("All_NewsAndEvents_data")
            print("cache data")
        else:
            newsAndEventsData = NewsAndEvents.objects.all()
            cache.set("All_NewsAndEvents_data", newsAndEventsData)
            print("database data")
        logger.info("Home page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
            'SuccessStoriesData': successStoriesData,
            'NewsAndEventsData': newsAndEventsData,
            'Servicesdata': servicesdata
        }
        return render(request, 'Localisation_App/home.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")



# About Us Page

def aboutus(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("hello")
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")
        if cache.get("All_About_data"):
            articleData = cache.get("All_About_data")
            print("cache data")
        else:
            articleData = Article.objects.all().filter(Article_HeadingName="About Us")
            cache.set("All_About_data", articleData)
            print("database data")
        logger.info("About Us page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
        }
        return render(request, 'Localisation_App/aboutus.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")

# Tools Page

def toolsPage(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data"):
            tools_Data=cache.get("All_ToolsData_data")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data",tools_Data)
            print("database data")
        Tools_Category.objects.all().update(Tools_Cat_Status=False)
        if cache.get("All_ToolsCategory_data"):
            toolsCategory_data=cache.get("All_ToolsCategory_data")
            print("cache data")
        else:
            toolsCategory_data = Tools_Category.objects.all()
            cache.set("All_ToolsCategory_data",toolsCategory_data)
            print("database data")
        count = ToolsData.objects.all().count()
        page = Paginator(tools_Data, 8)
        page_list = request.GET.get('page')
        page = page.get_page(page_list)
        count = tools_Data.count()
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'toolsdata': tools_Data,
            'tools_title': 'none',
            'toolscategory': toolsCategory_data,
            "page": page,
            'status_All_Checked': 'True',
            'Pagination_Type': 'All_Data',
            'count': count,
            'form': UserLoginForm()
        }
        logger.info("Tools page getting displayed")
        # if request.user.is_authenticated:
        #     return render(request, 'Localisation_App/tools.html', context)
        # else:
        return render(request, 'Localisation_App/tools.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")


def tools(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        checklist1 = []
        category_name = []
        pagestatus = False
        filtered_Tools_Data = ToolsData.objects.none()
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data1"):
            tools_Data=cache.get("All_ToolsData_data1")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data1",tools_Data)
            print("database data")
        
        toolsCategory_data = Tools_Category.objects.all()
        
        count = ToolsData.objects.all().count()

        if request.method == "POST":
            if request.POST.get('all_checkbox') != 'all_Checked':
                category_name = []
                filtered_Tools_Data = ToolsData.objects.none()
                print("dumydata", filtered_Tools_Data)
                checklist = request.POST.getlist('checkbox')
                Tools_Category.objects.all().update(Tools_Cat_Status=False)
                try:
                    for cat_check in checklist:
                        Tools_Category.objects.filter(

Localisation_App/templates/Localisation_App/user/Register.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Register{% endblock %}
{% load static %}

{% block register %}
<link rel="stylesheet" href="{% static 'Localisation_App/css/user/register.css' %}">

        <div class="container-fluid register-main">
          
          <div class="text-center p-3">
            <input type="text" class="text-center rounded-5 register-heading" value="Register" disabled />
          </div>
            <div class="row">
                <div class="col-md-6">
                  <img class="img-fluid" src="{% static './Localisation_App/img/registeration.png' %}" alt="..." />

                </div>
           <div class="col-1">

           </div>
                <div class=" col-sm-12 col-md-5 register-form-main">  
                  <div class="register-user-icon">
                    <img class="img-fluid" src="{% static './Localisation_App/img/Register-icon-1.png' %}" alt="..." />
                  </div>
                <form class="register-form" action={% url 'Localisation_App:register' %}  method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                  <div class="col-md-12">
                    {% if form.errors %}
                    <!-- {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    <strong>{{ field|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %} -->
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    {% comment %} <div class="col-md-4">
                    <div class="form-group position-relative">
                    <label>First name <span class="text-danger">*</span></label>
                    {{form.first_name}}
                    </div>
                    {% if form.first_name.errors %}
                    {% for error in form.first_name.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    <div class="col-md-4">
                    <div class="form-group position-relative">
                    <label>Middle name <span class="text-danger">*</span></label>
                    {{form.middle_name}}
                    </div>
                    {% if form.middle_name.errors %}
                    {% for error in form.middle_name.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    <div class="col-md-4">
                    <div class="form-group position-relative">
                    <label>Last name <span class="text-danger">*</span></label>
                    {{form.last_name}}
                    </div>
                    {% if form.last_name.errors %}
                    {% for error in form.last_name.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div> {% endcomment %}
                    <div class="col-md-12 mt-3">
                    <div class="form-group position-relative">
                    <label>Your Email <span class="text-danger">*</span></label>
                    {{form.username}}
                    </div>
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    {% comment %} <div class="col-md-12">
                    <div class="form-group position-relative">
                    <label>Username <span class="text-danger">*</span></label>
                    {{form.username}}
                    </div>
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div> {% endcomment %}
                   {% comment %} <div class="col-md-12">
                    <div class="form-group position-relative">
                    <label>Phone Number <span class="text-danger">*</span></label>
                    {{form.phone_number}}
                    </div>
                    {% if form.phone_number.errors %}
                    {% for error in form.phone_number.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div> {% endcomment %}
                    {% comment %} <div class="col-md-12">
                    <div class="form-group position-relative">
                    <label>Address <span class="text-danger">*</span></label>
                    {{form.address}}
                    </div>
                    {% if form.address.errors %}
                    {% for error in form.address.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div> {% endcomment %}
                    <div class="col-md-12">
                    <div class="form-group position-relative">
                    <label>Password <span class="text-danger">*</span></label>
                    {{form.password1}}
                    </div>
                    {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    <div class="col-md-12">
                    <div class="form-group position-relative">
                    <label>Confirm Password <span class="text-danger">*</span></label>
                    {{form.password2}}
                    </div>
                    {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    {% comment %} <div class="col-md-12">
                    <div class="form-group position-relative">
                    <label>Select User Type <span class="text-danger">*</span></label>
                    {{form.User_Type}}
                    </div>
                    {% if form.User_Type.errors %}
                    {% for error in form.User_Type.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div> {% endcomment %}
                     <div class="col-md-12">
                    <div class="form-group">
                    <div class="custom-control">
                    {{form.check}}
                   <label >I Accept <a href="{% static 'Localisation_App/PDF/TermsandCondition.pdf'%}" target="_top" class="text-primary">Terms And Condition</a><span class="text-danger">*</span></label>
                    </div>
                    {% if form.check.errors %}
                    {% for error in form.check.errors %}
                    <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endif %}
                    </div>
                    </div>
                    <div class="col-md-12">
                      <input class="register-button" type="submit" value="Register"/>
                    <!-- <button class="btn btn-primary w-100" type="submit" >Register</button> -->
                    </div>
                    <div class="mx-auto">
                    <p class="mb-0 mt-3"><small class="text-dark mr-2">Already have an account ?</small> <a href="{% url 'Localisation_App:login' %}" class="text-dark font-weight-bold">Login</a></p>
                    </div>
                    </div>
                    </form>
                    </div>
                    <div class="col-md-2"></div>
        </div>
      </div>
   
{% endblock %}

Localisation_App/templates/Localisation_App/user/changePassword.html
{% extends 'Localisation_App/base.html' %} {% load static %} {% block login %}

<link
  href="{% static 'Localisation_App/css/user/password.css' %}"
  rel="stylesheet"
/> 

<div class="password-main">
<div class="container" style="min-height: 60vh;">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h2 style="text-align: center">Login</h2>
      <form class="login-form" method="POST">
        {% csrf_token %}
        <div class="col-lg-12 mb-2">
          {% for message in messages %}
          <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
              {% comment %} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="True">&times;</span>
              </button> {% endcomment %}
              {{ message }}
            </div>
          </div>
          {% endfor %}
        <div class="row">
            <div class="col-md-12">
                <div class="form-group position-relative">
                <label>Password <span class="text-danger">*</span></label>
                {{form.password1}}
                </div>
                {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endif %}
                </div>
                <div class="col-md-12">
                <div class="form-group position-relative">
                <label>Confirm Password <span class="text-danger">*</span></label>
                {{form.password2}}
                </div>
                {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                {% endif %}
                </div>
                <input type="hidden" name="user_id" value="{{User_Id}}"/>
          <div class="col-lg-12 mb-0">
            <button class="btn btn-primary w-100" type="submit">Submit</button>
          </div>
          <div class="col-12 text-center">
            <p class="mb-0 mt-3">
             <a
            href="{% url 'Localisation_App:login' %}"
            class="text-dark font-weight-bold"
            >Login</a
          >  
              <small class="text-dark mr-2">Don't have an account ?</small>
              <a
                href="{% url 'Localisation_App:register' %}"
                class="text-dark font-weight-bold"
                >Register</a
              >
            </p>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
</div>

{% endblock %}

Localisation_App/templates/Localisation_App/user/login.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Login{% endblock %}
{% load static %}
{% block login %}
<link
      rel="stylesheet"
      href="{% static 'Localisation_App/css/user/login.css' %}"
    />

<div class="container-fluid p-3">
  <div class="text-center p-3">
    <input type="text" class="text-center rounded-5 login-heading" value="Login" disabled />
  </div>
  <div class="row">

    <div class="col-md-4 col-lg-6">
      <img class="img-fluid" src="{% static './Localisation_App/img/Login.png' %}" alt="..." />
    </div>
    
    <div class="col-md-8 col-lg-6 login-form-main">
      <div class="login-user-icon">
        <img class="img-fluid" src="{% static './Localisation_App/img/login-user-icon.png' %}" alt="..." />
      </div>
      <form class="login-form" action="{% url 'Localisation_App:login' %}" method="POST">
        {% csrf_token %}
        <div class="row mx-3">
         
          <div class="col-lg-12 mb-2">
            {% for message in messages %}
            <div class="container-fluid p-0">
              <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                {% comment %} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="True">&times;</span>
                </button> {% endcomment %}
                {{ message }}
              </div>
            </div>
            {% endfor %}


            <div class="form-group position-relative mt-5">
              <label class="mb-2">Email <span class="text-danger">*</span></label>
              {{form.username}}
            </div>
            {% if form.username.errors %}
            {% for error in form.username.errors %}
              <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
              </div>
              {% endfor %}
              {% endif %}
          </div>

          <div class="col-lg-12 mb-2">
            <div class="form-group position-relative">
              <label  class="mb-2">Password <span class="text-danger">*</span></label>
              {{form.password}}
            </div>
            <input class="login-button" type="submit" value="Submit"/>
          </div>
       
       
          
          <div class="col-12 left">
            <p class="mb-0 mt-3">Not a user yet? 
              <a href="{% url 'Localisation_App:register' %}" class="text-primary fw-semibold">Register here</a>
            </p>
          </div>
          <div class="col-12 left">
            <p class="mb-0 mt-1">
              <a href="{% url 'Localisation_App:forgetPassword' %}" class="text-primary fw-semibold">Forgot Your Password ?</a>
            </p>
          </div>
          
        </div>
      </form>
    </div>

  </div>

</div>

{% endblock %}

Localisation_App/templates/Localisation_App/user/logout.html
{% extends 'Localisation_App/base.html' %} 
{% block title %}Logout{% endblock %}
{% load static %} 
{% block logout %}
<link
    href="{% static 'Localisation_App/css/user/logout.css' %}"
    rel="stylesheet"
/>
<div class="container logout-main">
  <div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="home-center">
        <div class="home-desc-center">
            <div class="row justify-content-center">
              <div class="col-lg-4 col-md-6">
                <div class="login-page bg-white shadow rounded p-4">
                  <div class="text-center">
                    <h4 class="mb-4">You have been logged out</h4>
                    <br />
                    <div class="row">
                      <div class="col-md-6">
                        <a href="{% url 'Localisation_App:login' %}"
                          ><button class="btn btn-primary w-100">
                            Login
                          </button></a
                        >
                      </div>
                      <div class="col-md-6">
                        <a href="{% url 'Localisation_App:Home' %}"
                          ><button class="btn btn-info w-100">Home</button></a
                        >
                      </div>
                    </div>
                  </div>
                </div>
                <!--end col-->
              </div>
              <!--end row-->
            </div>
            <!--end container-->
          </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>
{% endblock %}