Localisation_App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


app_name = 'Localisation_App'
urlpatterns = [
     path('', views.Home, name='Home'),
     path('aboutus/', views.aboutus, name='aboutus'),
     path('toolsPage/', views.toolsPage, name='toolsPage'),
     path('tools/', views.tools, name='tools'),
     path('toolsDownloadCounter/<int:id>',
          views.toolsDownloadCounter, name='toolsDownloadCounter'),
     path('toolsReset/', views.toolsReset, name='toolsReset'),
     path('toolsSearch/<tools_title>', views.toolsSearch, name='toolsSearch'),
     path('resourcesPage/', views.resourcesPage, name='resourcesPage'),
     path('resources/', views.resources, name='resources'),
     path('resourceDownloadCounter/<int:id>',
          views.resourceDownloadCounter, name='resourceDownloadCounter'),
     path('resourcesReset/', views.resourcesReset, name='resourcesReset'),
     path('resourceSearch/<slug:resource_title>',
          views.resourceSearch, name='resourceSearch'),
     path('services/', views.services, name='services'),
     path('successstoryPage/', views.successstoryPage, name='successstoryPage'),
     path('successstory/', views.successstory, name='successstory'),
     path('successstorySearch/<story_title>',
          views.successstorySearch, name='successstorySearch'),
     #     path('successstoryReset/', views.successstoryReset, name='successstoryReset'),
     path('submit/', views.submit, name='submit'),
     path('faqs/', views.faqs, name='faqs'),
     path('faqsSearch/<faq_title>', views.faqsSearch, name='faqsSearch'),
     path('contactus/', views.contactus, name='contactus'),
     path('websitepolicy/', views.websitepolicy, name='websitepolicies'),
     path('websitepolicy/<int:id>', views.websitepolicydata,
          name='websitepolicydata'),
     path('termsandcondition/', views.termsandcondition, name='termsandcondition'),
     path('accessibilityStatement/', views.accessibilityStatement,
          name='accessibilityStatement'),
     path('sitemap/', views.sitemap, name='sitemap'),
     path('help/', views.help, name='help'),
     path('submit/<img>', views.submit, name='submit'),
     path('help/<int:id>', views.helpData, name='helpData'),
     path('srvEnableTyping/', views.srvEnableTyping, name='srvEnableTyping'),
     path('srvGoTranslateWebLocalizer/', views.srvGoTranslateWebLocalizer,
          name='srvGoTranslateWebLocalizer'),
     path('srvOnscreenKeyboard/', views.srvOnscreenKeyboard,
          name='srvOnscreenKeyboard'),
     path('srvTTS/', views.srvTTS, name='srvTTS'),
     path('srvTransliteration/', views.srvTransliteration,
          name='srvTransliteration'),
     path('register/', views.Register_user, name="register"),
     path('login/', views.login_user, name='login'),
     path('logout/', views.logout_user, name='logout'),
     path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
     path('changePassword/<token>/', views.changePassword, name='changePassword'),
     path('profile/<int:id>', views.User_Profile, name="profile"),

     path('goTranslate/', views.goTranslate,
          name='goTranslate'),
     path('translation-quote/', views.translation_quote,
          name='translation_quote'),
     path('translation-quote-user-dashboard', views.translation_quote_user_dashboard,
          name='translation_quote_user_dashboard'),
     path('translation-quote-show/<str:application_number>/',
          views.translation_quote_show, name='translation_quote_show'),
     #     path('dashboard2', views.dashboard2, name="dashboard2"),
     path('dashboard', views.dashboard, name="dashboard"),
     path('machine-translation/', views.machine_translation,
          name="machine_translation"),
     path('name-matcher/', views.name_matcher, name="name_matcher"),
     path('empanelled_agencies/', views.empanelled_agencies,
          name="empanelled_agencies"),
     path('bhashini/',views.bhashini,name="bhashini"),
     path('anuvaad/',views.anuvaad, name="anuvaad")

     #     path("Slug_test/<slug:slug>", views.Slug_test, name="Slug_test"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

Localisation_Project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Localisation_App.urls'))

]

Localisation_App/views.py
from threading import currentThread
from wsgiref import validate
from django.db.models import Sum
from django.forms import ValidationError
from Localisation_Project.settings import CACHE_TTL
from .forms import TTSservice, RegisterForm, TranslationQuoteForm, UserLoginForm, UserChangePasswordForm, UserForgetPasswordForm
from django.contrib import messages
from django.core.mail import send_mail, mail_admins
from django.core.paginator import Paginator
from multiprocessing import context
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from .models import *
import random
import requests
from .word_count import crawl_data
from django.contrib.auth.models import User
import uuid
from datetime import date, datetime
from .helpers import send_forget_password_email
import json
from bson import json_util
from django.urls import resolve
import uuid
from django.contrib.auth.decorators import login_required
import logging
from datetime import date
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.core import validators
logger = logging.getLogger('django')
global str_num
global url
CACHE_TTL = getattr(settings,'CACHE_TTL',DEFAULT_TIMEOUT)


# Home Page

def Home(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("url", url)
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_Article_data"):
            articleData = cache.get("All_Article_data")
            print("cache data")
        else:
            articleData = Article.objects.all()
            cache.set("All_Article_data", articleData)
            print("database data")

        if cache.get("All_SuccessStories_data"):
            successStoriesData = cache.get("All_SuccessStories_data")
            print("cache data")
        else:
            successStoriesData = SuccessStories.objects.all()
            cache.set("All_SuccessStories_data", successStoriesData)
            print("database data")

        if cache.get("All_Services_data"):
            servicesdata = cache.get("All_Services_data")
            print("cache data")
        else:
            servicesdata = Services.objects.all()
            cache.set("All_Services_data", servicesdata)
            print("database data")

        if cache.get("All_NewsAndEvents_data"):
            newsAndEventsData = cache.get("All_NewsAndEvents_data")
            print("cache data")
        else:
            newsAndEventsData = NewsAndEvents.objects.all()
            cache.set("All_NewsAndEvents_data", newsAndEventsData)
            print("database data")
        logger.info("Home page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
            'SuccessStoriesData': successStoriesData,
            'NewsAndEventsData': newsAndEventsData,
            'Servicesdata': servicesdata
        }
        return render(request, 'Localisation_App/home.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")



# About Us Page

def aboutus(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("hello")
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")
        if cache.get("All_About_data"):
            articleData = cache.get("All_About_data")
            print("cache data")
        else:
            articleData = Article.objects.all().filter(Article_HeadingName="About Us")
            cache.set("All_About_data", articleData)
            print("database data")
        logger.info("About Us page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
        }
        return render(request, 'Localisation_App/aboutus.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")

# Tools Page

def toolsPage(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data"):
            tools_Data=cache.get("All_ToolsData_data")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data",tools_Data)
            print("database data")
        Tools_Category.objects.all().update(Tools_Cat_Status=False)
        if cache.get("All_ToolsCategory_data"):
            toolsCategory_data=cache.get("All_ToolsCategory_data")
            print("cache data")
        else:
            toolsCategory_data = Tools_Category.objects.all()
            cache.set("All_ToolsCategory_data",toolsCategory_data)
            print("database data")
        count = ToolsData.objects.all().count()
        page = Paginator(tools_Data, 8)
        page_list = request.GET.get('page')
        page = page.get_page(page_list)
        count = tools_Data.count()
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'toolsdata': tools_Data,
            'tools_title': 'none',
            'toolscategory': toolsCategory_data,
            "page": page,
            'status_All_Checked': 'True',
            'Pagination_Type': 'All_Data',
            'count': count,
            'form': UserLoginForm()
        }
        logger.info("Tools page getting displayed")
        # if request.user.is_authenticated:
        #     return render(request, 'Localisation_App/tools.html', context)
        # else:
        return render(request, 'Localisation_App/tools.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")


def tools(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        checklist1 = []
        category_name = []
        pagestatus = False
        filtered_Tools_Data = ToolsData.objects.none()
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data1"):
            tools_Data=cache.get("All_ToolsData_data1")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data1",tools_Data)
            print("database data")
        
        toolsCategory_data = Tools_Category.objects.all()
        
        count = ToolsData.objects.all().count()

        if request.method == "POST":
            if request.POST.get('all_checkbox') != 'all_Checked':
                category_name = []
                filtered_Tools_Data = ToolsData.objects.none()
                print("dumydata", filtered_Tools_Data)
                checklist = request.POST.getlist('checkbox')
                Tools_Category.objects.all().update(Tools_Cat_Status=False)
                try:
                    for cat_check in checklist:
                        Tools_Category.objects.filter(

Localisation_App/templates/Localisation_App/footer.html
{% load static %}

<link
      href="{% static 'Localisation_App/css/footer-links.css' %}"
      rel="stylesheet"
    />
    
<div class="sticky-button">
  <img src="{% static './Localisation_App/img/gotranslate.jpg' %}" alt="..." class="sticky-img" /><span><a target="_blank" href="https://chrome.google.com/webstore/detail/gotranslate-web-localizer/lcmdfppjojeebpjblgmookbnfmbnjhhh?hl=en">GoTranslate Plugin</a> </span>
  
 </div>
 <div class="sticky-button-2">
  <img src="{% static './Localisation_App/img/gem.jpg' %}" alt="..." class="sticky-img"/><span><a target="_blank" href="https://gem.gov.in/">GEM Portal</a> </span>
  
 </div>
 <div class="sticky-button-3">
  <img src="{% static './Localisation_App/img/Shake.png' %}" alt="..." class="sticky-img" /><span><a target="_blank" href="https://chrome.google.com/webstore/detail/gotranslate-web-localizer/lcmdfppjojeebpjblgmookbnfmbnjhhh?hl=en">Empanelled Agencies</a> </span>
  
 </div>
 <div class="sticky-button-4">
  <img src="{% static './Localisation_App/img/nplt3.jpg' %}" alt="..." class="sticky-img" /><span><a target="_blank" href="https://chrome.google.com/webstore/detail/gotranslate-web-localizer/lcmdfppjojeebpjblgmookbnfmbnjhhh?hl=en">NPLT</a> </span>
  
 </div>
 <div class="row footer-link-section">
   <div class="col-1">

   </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/community1.png' %}" alt="..." style="color:white" class="footer-link-img" />
   <a target="_blank" href="https://www.tdil-dc.in/index.php?option=com_communityprofile&Itemid=548&lang=en">TDIL Community</a> 
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/sitemaps1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank" href="{% url 'Localisation_App:sitemap' %}">Sitemaps</a> 
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/call1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank" href="{% url 'Localisation_App:contactus' %}">
      Contact Us
    </a>
   
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/dashboard1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank" href="{% url 'Localisation_App:dashboard' %}">  Dashboard</a>
  
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/training1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank"  href="{% url 'Localisation_App:contactus' %}" >     Training</a>

  </div>
  

</div>
 
 <div class="footer">
 
   <div class="row">
     <div class="col-sm-12 col-lg-3  footer-left">
       <h3 class="quick">Quick Links</h3>

       <p>
       <ul style="list-style: none;">
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:Home' %}">{{ topmenus.0 }}</a></li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:websitepolicies' %}">{{ FooterMenuItemsdata.0 }}</a>
         </li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:termsandcondition' %}">{{ FooterMenuItemsdata.1 }}</a>
         </li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:accessibilityStatement' %}">{{ FooterMenuItemsdata.2 }}</li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:sitemap' %}">{{ FooterMenuItemsdata.3 }}</a></li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:help' %}">{{ FooterMenuItemsdata.4 }}</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
          href="{% url 'Localisation_App:empanelled_agencies' %}">{{ FooterMenuItemsdata.5 }}</a></li>
          <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
            href="{% url 'Localisation_App:faqs' %}">{{ FooterMenuItemsdata.6 }}</a></li>
       </ul>
       </p>
     </div>
     <div class="col-sm-12 col-md-12 col-lg-6  footer-center">
       <img src="{% static './Localisation_App/img/meity.png' %}" class="footer-image-center" alt="..." />
       <hr class="line">
       <div class="row ">

         <div class="col-sm-3 col-md-3 col-lg-3 footer-logo-1 text-center px-2"> <a href="https://digitalindia.gov.in/" target="_blank"><img
             src="{% static './Localisation_App/img/digital-india.png' %}" class="img-fluid" alt="..." /></a></div>
         <div class="col-sm-12 col-md-3 col-lg-3 footer-logo-4 text-center px-5"> <a href="https://www.mygov.in/" target="_blank"><img
             src="{% static './Localisation_App/img/mygov.png' %}" height="60px" width="120px" alt="..." /></a></div>
         <div class="col-sm-12 col-md-3 col-lg-3 footer-logo-2 text-center pt-1 px-1"> <a href="https://www.tdil-dc.in/index.php?lang=en" target="_blank"><img
             src="{% static './Localisation_App/img/tdil.png' %}" class="img-1" alt="..." /></a></div>
         {% comment %} <div class="col-sm-12 col-md-3 col-lg-3 footer-logo-3"> <img
             src="{% static './Localisation_App/img/bhashini-logo.png' %}" height="80px" width="120px" class="" alt="..." /></div> {% endcomment %}
             <div class="col-sm-3 col-md-3 col-lg-3 footer-logo-1 text-center"> <a href="https://meitystartuphub.in/" target="_blank"><img
              src="{% static './Localisation_App/img/Meity_startup_hub.png' %}" class="img-fluid" alt="..." /></a></div>
             
       </div>
     </div>

     <div class="col-lg-6 footer-right">
      <h3 class="quick">IDN Links</h3>
 
      <p>
      <ul style="list-style: none;">
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://www.cdac.in/">सीडैक.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://www.meity.gov.in/">एमईआईटीवाई.सरकार.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://www.india.gov.in/">इंडिया.सरकार.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://innovate.mygov.in/">इनोवेटइंडिया.मेरीसरकार.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://registry.in/">रजिस्ट्री.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://nixi.in/">निक्सी.भारत</a></li>

      </ul>
      </p>
       <!-- <h5 class="designed">
         Designed, Developed & Hosted by
       </h5>
       <h6>CDAC GIST Pune</h6> -->
       <br>
       <!-- <img src="{% static './Localisation_App/img/Group12.jpg' %}" class="footer-gist-section" alt="..." /> -->
     </div>
   </div>
   <div class="copyright-section">
    <h5 class="designed">
      Designed, Developed & Hosted by <span style="font-weight: 700;"><a target="_blank" href="https://www.cdac.in/" style="text-decoration: none;color:white;"> CDAC GIST</a></span> Pune
    </h5>
 
     Copyright © 2022 LPMF. All Rights Reserved.
   </div>
 </div>

Localisation_App/templates/Localisation_App/home.html
{% extends 'Localisation_App/base.html' %} {% block title %}Home{% endblock %}
{% load static %} {% block home %}

<!--carousel start-->
{% include 'Localisation_App/home/home_carousal.html' %}
<!--carousel end -->

<!--News start-->
{% include 'Localisation_App/home/home_news.html' %}
<!--News end-->

<!--About Us start-->
{% include 'Localisation_App/home/home_aboutus.html' %}
<!--About Us end-->

<!--Vision start-->
{% include 'Localisation_App/home/home_vision.html' %}
<!--Vision end-->

<!-- Bhashini Home Section Starts -->
{% include 'Localisation_App/home/home_bhashini.html' %}
<!-- Bhashinin Home Section Ends -->

<!--marketing carousel start-->
{% include 'Localisation_App/home/home_marketting.html' %}
<!--marketing carousel end-->

<!-- Success Stories Start -->
{% include 'Localisation_App/home/home_success_stories.html' %}
<!-- Success Stories Ends -->

<!--Mission start-->
{% include 'Localisation_App/home/home_mission.html' %}
<!--mission end-->

<!-- Estimate Cost Section Start -->
{% include 'Localisation_App/home/home_cost_estimation.html' %}
<!-- Esitmate Cost Sectio End -->

{% endblock %}

Localisation_App/templates/Localisation_App/topmenu.html
{% load static %}

<nav
  class="navbar navbar-expand-lg bg-light sticky-top"
  style="
    background-color: #ffffff !important;
    box-shadow: 0px 0.5px 13px 1px rgb(230, 228, 228);
  "
>
  <div class="container-fluid">
    <a class="navbar-brand mx-5" href="{% url 'Localisation_App:Home' %}">
      <img
        src="{% static './Localisation_App/img/llogo.png' %}"
        class="d-block w-100"
        alt="..."
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item {% if request.path == '/' %}active{% endif %}">
          <a
            class="items"
            aria-current="page"
            href="{% url 'Localisation_App:Home' %}"
            >{{ topmenus.0 }}</a
          >
        </li>
        <li
          class="nav-item {% if request.path == '/aboutus/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:aboutus' %}"
            >{{ topmenus.1 }}</a
          >
        </li>

        <li
          class="nav-item dropdown {% if request.path == '/services/' or request.path == '/toolsPage/' or request.path == '/resourcesPage/' %}active{% endif %}"
        >
          <a
            class="nav-link dropdown-toggle items"
            style="padding: 0px"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Our Products
          </a>
          <ul
            class="dropdown-menu"
            style="padding-left: 12px"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li class="nav-item active">
              <a class="items" href="{% url 'Localisation_App:services' %}"
                >{{ topmenus.2 }}</a
              >
            </li>
            <li
              class="nav-item {% if request.path == '/toolsPage/' %}active{% endif %}"
            >
              <a class="items" href="{% url 'Localisation_App:toolsPage' %}"
                >{{ topmenus.3 }}</a
              >
            </li>
            <li
              class="nav-item {% if request.path == '/resourcesPage/' %}active{% endif %}"
            >
              <a class="items" href="{% url 'Localisation_App:resourcesPage' %}"
                >{{ topmenus.10 }}</a
              >
            </li>
          </ul>
        </li>

        <li
          class="nav-item {% if request.path == '/successstoryPage/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:successstoryPage' %}"
            >{{ topmenus.4 }}</a
          >
        </li>
        <li
          class="nav-item {% if request.path == '/dashboard/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:dashboard' %}"
            >{{ topmenus.12 }}</a
          >
        </li>
        <li class="nav-item {% if request.path == '/faqs/' %}active{% endif %}">
          <a class="items" href="{% url 'Localisation_App:faqs' %}"
            >{{ topmenus.5 }}</a
          >
        </li>
        <li
          class="nav-item {% if request.path == '/contactus/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:contactus' %}"
            >{{ topmenus.6 }}</a
          >
        </li>
        {% if not user.is_authenticated %}
        {% comment %} <li class="nav-item">
          <a class="items" href="{% url 'Localisation_App:register' %}">
            {{ topmenus.7 }}
          </a>
        </li> {% endcomment %}
        <li class="nav-item">
          <a class="items" href="{% url 'Localisation_App:login' %}"
            >{{ topmenus.8 }}</a
          >
        </li>
        {% else %} 

        <li
          class="nav-item dropdown {% if request.path == '/services/' or request.path == '/toolsPage/' or request.path == '/resourcesPage/' %}active{% endif %}"
        >
          <a
            class="nav-link dropdown-toggle items"
            style="padding: 0px"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <img
              src="{% static './Localisation_App/img/profileicon.png' %}"
              alt="..."
              class="Profile-link-img"
            />
          </a>

          <ul
            class="dropdown-menu"
            style="padding-left: 12px"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li
              class="nav-item {% if request.path == '/toolsPage/' %}active{% endif %}"
            >
              <a
                class="items"
                href="{% url 'Localisation_App:profile' user.id %}"
                >Profile</a
              >
            </li>
            <li class="nav-item active">
              <a class="items" href="{% url 'Localisation_App:logout' %}"
                >{{ topmenus.11 }}</a
              >
            </li>
          </ul>
          {% endif %}
        </li>
      </ul>

      <div class="nav-item animate__animated animate__pulse animate__infinite">
        <div class="quote">
          <a
            class="item-button"
            href="{% url 'Localisation_App:translation_quote' %}"
            >{{ topmenus.9 }}</a
          >
        </div>
      </div>
    </div>
  </div>
</nav>