Localisation_App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


app_name = 'Localisation_App'
urlpatterns = [
     path('', views.Home, name='Home'),
     path('aboutus/', views.aboutus, name='aboutus'),
     path('toolsPage/', views.toolsPage, name='toolsPage'),
     path('tools/', views.tools, name='tools'),
     path('toolsDownloadCounter/<int:id>',
          views.toolsDownloadCounter, name='toolsDownloadCounter'),
     path('toolsReset/', views.toolsReset, name='toolsReset'),
     path('toolsSearch/<tools_title>', views.toolsSearch, name='toolsSearch'),
     path('resourcesPage/', views.resourcesPage, name='resourcesPage'),
     path('resources/', views.resources, name='resources'),
     path('resourceDownloadCounter/<int:id>',
          views.resourceDownloadCounter, name='resourceDownloadCounter'),
     path('resourcesReset/', views.resourcesReset, name='resourcesReset'),
     path('resourceSearch/<slug:resource_title>',
          views.resourceSearch, name='resourceSearch'),
     path('services/', views.services, name='services'),
     path('successstoryPage/', views.successstoryPage, name='successstoryPage'),
     path('successstory/', views.successstory, name='successstory'),
     path('successstorySearch/<story_title>',
          views.successstorySearch, name='successstorySearch'),
     #     path('successstoryReset/', views.successstoryReset, name='successstoryReset'),
     path('submit/', views.submit, name='submit'),
     path('faqs/', views.faqs, name='faqs'),
     path('faqsSearch/<faq_title>', views.faqsSearch, name='faqsSearch'),
     path('contactus/', views.contactus, name='contactus'),
     path('websitepolicy/', views.websitepolicy, name='websitepolicies'),
     path('websitepolicy/<int:id>', views.websitepolicydata,
          name='websitepolicydata'),
     path('termsandcondition/', views.termsandcondition, name='termsandcondition'),
     path('accessibilityStatement/', views.accessibilityStatement,
          name='accessibilityStatement'),
     path('sitemap/', views.sitemap, name='sitemap'),
     path('help/', views.help, name='help'),
     path('submit/<img>', views.submit, name='submit'),
     path('help/<int:id>', views.helpData, name='helpData'),
     path('srvEnableTyping/', views.srvEnableTyping, name='srvEnableTyping'),
     path('srvGoTranslateWebLocalizer/', views.srvGoTranslateWebLocalizer,
          name='srvGoTranslateWebLocalizer'),
     path('srvOnscreenKeyboard/', views.srvOnscreenKeyboard,
          name='srvOnscreenKeyboard'),
     path('srvTTS/', views.srvTTS, name='srvTTS'),
     path('srvTransliteration/', views.srvTransliteration,
          name='srvTransliteration'),
     path('register/', views.Register_user, name="register"),
     path('login/', views.login_user, name='login'),
     path('logout/', views.logout_user, name='logout'),
     path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
     path('changePassword/<token>/', views.changePassword, name='changePassword'),
     path('profile/<int:id>', views.User_Profile, name="profile"),

     path('goTranslate/', views.goTranslate,
          name='goTranslate'),
     path('translation-quote/', views.translation_quote,
          name='translation_quote'),
     path('translation-quote-user-dashboard', views.translation_quote_user_dashboard,
          name='translation_quote_user_dashboard'),
     path('translation-quote-show/<str:application_number>/',
          views.translation_quote_show, name='translation_quote_show'),
     #     path('dashboard2', views.dashboard2, name="dashboard2"),
     path('dashboard', views.dashboard, name="dashboard"),
     path('machine-translation/', views.machine_translation,
          name="machine_translation"),
     path('name-matcher/', views.name_matcher, name="name_matcher"),
     path('empanelled_agencies/', views.empanelled_agencies,
          name="empanelled_agencies"),
     path('bhashini/',views.bhashini,name="bhashini"),
     path('anuvaad/',views.anuvaad, name="anuvaad")

     #     path("Slug_test/<slug:slug>", views.Slug_test, name="Slug_test"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

Localisation_Project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Localisation_App.urls'))

]

Localisation_App/views.py
from threading import currentThread
from wsgiref import validate
from django.db.models import Sum
from django.forms import ValidationError
from Localisation_Project.settings import CACHE_TTL
from .forms import TTSservice, RegisterForm, TranslationQuoteForm, UserLoginForm, UserChangePasswordForm, UserForgetPasswordForm
from django.contrib import messages
from django.core.mail import send_mail, mail_admins
from django.core.paginator import Paginator
from multiprocessing import context
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from .models import *
import random
import requests
from .word_count import crawl_data
from django.contrib.auth.models import User
import uuid
from datetime import date, datetime
from .helpers import send_forget_password_email
import json
from bson import json_util
from django.urls import resolve
import uuid
from django.contrib.auth.decorators import login_required
import logging
from datetime import date
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.core import validators
logger = logging.getLogger('django')
global str_num
global url
CACHE_TTL = getattr(settings,'CACHE_TTL',DEFAULT_TIMEOUT)


# Home Page

def Home(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("url", url)
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_Article_data"):
            articleData = cache.get("All_Article_data")
            print("cache data")
        else:
            articleData = Article.objects.all()
            cache.set("All_Article_data", articleData)
            print("database data")

        if cache.get("All_SuccessStories_data"):
            successStoriesData = cache.get("All_SuccessStories_data")
            print("cache data")
        else:
            successStoriesData = SuccessStories.objects.all()
            cache.set("All_SuccessStories_data", successStoriesData)
            print("database data")

        if cache.get("All_Services_data"):
            servicesdata = cache.get("All_Services_data")
            print("cache data")
        else:
            servicesdata = Services.objects.all()
            cache.set("All_Services_data", servicesdata)
            print("database data")

        if cache.get("All_NewsAndEvents_data"):
            newsAndEventsData = cache.get("All_NewsAndEvents_data")
            print("cache data")
        else:
            newsAndEventsData = NewsAndEvents.objects.all()
            cache.set("All_NewsAndEvents_data", newsAndEventsData)
            print("database data")
        logger.info("Home page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
            'SuccessStoriesData': successStoriesData,
            'NewsAndEventsData': newsAndEventsData,
            'Servicesdata': servicesdata
        }
        return render(request, 'Localisation_App/home.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")



# About Us Page

def aboutus(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("hello")
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")
        if cache.get("All_About_data"):
            articleData = cache.get("All_About_data")
            print("cache data")
        else:
            articleData = Article.objects.all().filter(Article_HeadingName="About Us")
            cache.set("All_About_data", articleData)
            print("database data")
        logger.info("About Us page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
        }
        return render(request, 'Localisation_App/aboutus.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")

# Tools Page

def toolsPage(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data"):
            tools_Data=cache.get("All_ToolsData_data")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data",tools_Data)
            print("database data")
        Tools_Category.objects.all().update(Tools_Cat_Status=False)
        if cache.get("All_ToolsCategory_data"):
            toolsCategory_data=cache.get("All_ToolsCategory_data")
            print("cache data")
        else:
            toolsCategory_data = Tools_Category.objects.all()
            cache.set("All_ToolsCategory_data",toolsCategory_data)
            print("database data")
        count = ToolsData.objects.all().count()
        page = Paginator(tools_Data, 8)
        page_list = request.GET.get('page')
        page = page.get_page(page_list)
        count = tools_Data.count()
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'toolsdata': tools_Data,
            'tools_title': 'none',
            'toolscategory': toolsCategory_data,
            "page": page,
            'status_All_Checked': 'True',
            'Pagination_Type': 'All_Data',
            'count': count,
            'form': UserLoginForm()
        }
        logger.info("Tools page getting displayed")
        # if request.user.is_authenticated:
        #     return render(request, 'Localisation_App/tools.html', context)
        # else:
        return render(request, 'Localisation_App/tools.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")


def tools(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        checklist1 = []
        category_name = []
        pagestatus = False
        filtered_Tools_Data = ToolsData.objects.none()
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data1"):
            tools_Data=cache.get("All_ToolsData_data1")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data1",tools_Data)
            print("database data")
        
        toolsCategory_data = Tools_Category.objects.all()
        
        count = ToolsData.objects.all().count()

        if request.method == "POST":
            if request.POST.get('all_checkbox') != 'all_Checked':
                category_name = []
                filtered_Tools_Data = ToolsData.objects.none()
                print("dumydata", filtered_Tools_Data)
                checklist = request.POST.getlist('checkbox')
                Tools_Category.objects.all().update(Tools_Cat_Status=False)
                try:
                    for cat_check in checklist:
                        Tools_Category.objects.filter(

Localisation_App/templates/Localisation_App/home/carousal.html
<div class="container-fluid">
    <div class="row">
      <div class="col-12" style="background-color: #f1f2f3">
        <div
          id="carouselExampleDark"
          class="carousel carousel-dark slide"
          data-bs-ride="carousel"
        >
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="4000">
              <div class="carousel-inner-text">
                <h3 class="carousel-title">Localisation in</h3>
                <h3 class="carousel-subtitle-1">e-Governance</h3>
  
                <p class="carousel-caption-1">
                  भारतीय भाषाओं में उपकरण और प्रौद्योगिकी के लिए निरंतर प्रयासरत
                </p>
              </div>
            </div>
  
            <div class="carousel-item" data-bs-interval="4000">
              <div class="carousel-inner-text-2">
                <!-- <div class="text-center">Localisation in</div> -->
                <h3 class="carousel-title">Bhashini</h3>
                <h3 class="carousel-subtitle-2">
                  One Platform, Multiple Crowdsourcing
                </h3>
  
                <p class="carousel-caption-2">
                  भाषा की बाधाओं को पार करके सबके डिजिटल सशक्तिकरण की ओर
                </p>
              </div>
            </div>
  
            <div class="carousel-item" data-bs-interval="4000">
              <div class="carousel-inner-text-3">
                <!-- <div class="text-center">Localisation in</div> -->
                <h3 class="carousel-title">Translate Your Website</h3>
                <h3 class="carousel-subtitle-3">Estimate Quote</h3>
  
                <p class="carousel-caption-3">आपकी वेबसाइट आपकी भाषा में</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

Localisation_App/templates/Localisation_App/home/home_aboutus.html
{% load static %} 
<div class="container-fluid testting py-3">
    <div class="col-12" data-aos="fade-down" data-aos-duration="1000">
      <h4 class="aboutUs-Title">{{ ArticleData.0.Article_HeadingName }}</h4>
    </div>
    <div class="row">
      <div
        class="col-sm-12 col-lg-6"
        data-aos="fade-down"
        data-aos-duration="1200"
      >
        {% if ArticleData.0.Article_Image != NUll %}
        <img
          class="d-block w-100"
          src="/media/{{ ArticleData.0.Article_Image }}"
          alt="..."
        />
        {% endif %}
      </div>
      <div
        class="col-sm-12 col-lg-6 p-3"
        data-aos="fade-down"
        data-aos-duration="1200"
      >
        <div class="aboutUs-para">
          {{ ArticleData.0.Article_Description|safe|slice:":1349" }}
        </div>
        <button class="aboutus-Button">
          <a href="{% url 'Localisation_App:aboutus' %}">Read More</a>
        </button>
      </div>
    </div>
  
    <div class="container my-3">
      <div class="services-title">Our Services</div>
      <div class="row">
        <div
          class="col col-xs-12 col-sm-12 col-md-12 col-lg-3 card1"
          data-aos="fade-down"
          data-aos-duration="1000"
        ><a href="{% url 'Localisation_App:services' %}">
          <div class="icon">
            <img
              src="{% static './Localisation_App/img/Keyboard1.png' %}"
              class="d-block w-100 pt-2"
              alt="..."
            />
          </div>
          <p class="card-description mt-2">{{ Servicesdata.0.Services_Name }}</p>
        </a>
        </div>
        <div
          class="col col-xs-12 col-sm-12 col-md-12 col-lg-3 card2"
          data-aos="fade-down"
          data-aos-duration="1500"
        ><a href="{% url 'Localisation_App:services' %}">
          <div class="icon">
            <img
              src="{% static './Localisation_App/img/Go-trans2.png' %}"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <p class="card-description mt-2">{{ Servicesdata.1.Services_Name }}</p>
        </a>
        </div>
        <div
          class="col col-xs-12 col-sm-12 col-md-12 col-lg-3 card3"
          data-aos="fade-down"
          data-aos-duration="2000"
        ><a href="{% url 'Localisation_App:services' %}">
          <div class="icon">
            <img
              src="{% static './Localisation_App/img/Go-trans.png' %}"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <p class="card-description mt-2">{{ Servicesdata.2.Services_Name }}</p>
        </a>
        </div>
        <div
          class="col col-xs-12 col-sm-12 col-md-12 col-lg-3 card4"
          data-aos="fade-down"
          data-aos-duration="2500"
        ><a href="{% url 'Localisation_App:services' %}">
          <div class="icon">
            <img
              src="{% static './Localisation_App/img/Clients.png' %}"
              class="d-block w-100"
              alt="..."
            />
          </div>
          <p class="card-description mt-2">{{ Servicesdata.3.Services_Name }}</p>
        </a>
        </div>
  
        <button class="aboutus-Button2">
          <a href="{% url 'Localisation_App:services' %}">More...</a>
        </button>
      </div>
    </div>
  </div>
  

Localisation_App/templates/Localisation_App/home/home_bhashini.html
{% load static %} 
<div class="container-fluid test pt-5">
    <div class="row bhasha-row ">
      <div class="col d-flex justify-content-center mb-4">
        <div class="bhasha-description-section d-flex justify-content-center flex-wrap">
          <img class="bhasha-img" src="{% static './Localisation_App/img/BhashiniLogo.png' %}"
          alt="..." />
          <div class="text-center">
            <p>Bhashini aims to build a National Public Digital Platform for languages to develop services and products for citizens by leveraging the power of artificial intelligence and other emerging technologies.</p>
          </div>
        </div>
      </div>
    </div>
  
    <div class=" bhasha-below-rows row justify-content-around">
      <div class="col-4 bhasha-section">
        <div class="bhasha-icon d-flex justify-content-center">
          <img class="bhasha-img-1" src="{% static './Localisation_App/img/ulca2.png' %}"
          alt="...">
        </div>
       <div class="bhasha-section-content">
        UNIVERSAL LANGUAGE CONTRIBUTION API
       </div>
       <p class="bhasha-sub-section-content">
        Standard API and open scalable data platform
       </p>
       <a class="bhasha-button" href="{% url 'Localisation_App:bhashini' %}"> Know More ..</a>
      </div>
      <div class="col-4  bhasha-section">
        <div class="bhasha-icon d-flex justify-content-center">
          <img class="bhasha-img-1" src="{% static './Localisation_App/img/ulca2.png' %}"
          alt="...">
        </div>
        <div class="bhasha-section-content d-flex justify-content-center">
          BHASHA DAAN
         </div>
         <p class="bhasha-sub-section-content">
          Open repository of multilingual data
         </p>
         <a class="bhasha-button" href="{% url 'Localisation_App:bhashini' %}"> Know More ..</a>
      </div>
    </div>
  </div>

Localisation_App/templates/Localisation_App/home/home_carousal.html
<div class="container-fluid">
    <div class="row">
      <div class="col-12" style="background-color: #f1f2f3">
        <div
          id="carouselExampleDark"
          class="carousel carousel-dark slide"
          data-bs-ride="carousel"
        >
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="4000">
              <div class="carousel-inner-text">
                <h3 class="carousel-title">Localisation in</h3>
                <h3 class="carousel-subtitle-1">e-Governance</h3>
  
                <p class="carousel-caption-1">
                  भारतीय भाषाओं में उपकरण और प्रौद्योगिकी के लिए निरंतर प्रयासरत
                </p>
              </div>
            </div>
  
            <div class="carousel-item" data-bs-interval="4000">
              <div class="carousel-inner-text-2">
                <!-- <div class="text-center">Localisation in</div> -->
                <h3 class="carousel-title">Bhashini</h3>
                <h3 class="carousel-subtitle-2">
                  One Platform, Multiple Crowdsourcing
                </h3>
  
                <p class="carousel-caption-2">
                  भाषा की बाधाओं को पार करके सबके डिजिटल सशक्तिकरण की ओर
                </p>
              </div>
            </div>
  
            <div class="carousel-item" data-bs-interval="4000">
              <div class="carousel-inner-text-3">
                <!-- <div class="text-center">Localisation in</div> -->
                <h3 class="carousel-title">Translate Your Website</h3>
                <h3 class="carousel-subtitle-3">Estimate Quote</h3>
  
                <p class="carousel-caption-3">आपकी वेबसाइट आपकी भाषा में</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

Localisation_App/templates/Localisation_App/home/home_cost_estimation.html
{% load static %} 
<div class="container-fluid p-3">
    <div class="row">
      <div class="col-lg-6">
        <img
          src="/media/{{ ArticleData.1.Article_Image }}"
          class="esitimate-cost-img"
          alt="..."
        />
      </div>
  
      <div class="col-lg-6 estimate-cost-content">
        <h1 class="estimate-cost-title">
          {{ ArticleData.1.Article_HeadingName }}
        </h1>
        <!-- <div class="estimate-cost-money-img">
            <img src="{% static './Localisation_App/img/cost.png' %}" class="test" alt="..." />
          </div> -->
        <div class="estimate-cost-button">
          <a href="{% url 'Localisation_App:translation_quote' %}"
            >Your Website Domain</a
          >
        </div>
      </div>
    </div>
  </div>

Localisation_App/templates/Localisation_App/home/home_marketting.html
{% load static %} 
<div id="carouselExampleControls" class="carousel slide text-center p-5" data-bs-ride="carousel" style="background-color:#9ed2df; background-image: url('{% static './Localisation_App/img/Frame 3.png' %}'); background-repeat: no-repeat;  background-size: cover">
    <div class="carousel-inner px-5">
      <div class="carousel-item active">
        {% comment %} <img
        width="100%"
        src="{% static './Localisation_App/img/marketing carousel1.png' %}"
        alt=""
      /> {% endcomment %}
         <div class="row text-center">
            <div class="col-4 d-flex-content center">
              <img
               src="{% static './Localisation_App/img/marketing carousel1.png' %}"
               width="200px"
               height="200px"
               alt=""
              />
            </div>
            <div class="col-7 fs-3 py-4 fw-semibold">CDAC GIST Keyboard available in 22 indian languages which is compatible to all devices</div>
         </div>
      </div>
      <div class="carousel-item">
        {% comment %} <img
        width="100%"
        src="{% static './Localisation_App/img/marketing carousel2.png' %}"
        alt=""
      /> {% endcomment %}
      
         <div class="row text-center">
            <div class="col-4 d-flex-content center">
              <img
                src="{% static './Localisation_App/img/marketing carousel2.png' %}"
                width="200px"
                height="200px"
                alt=""
              />
            </div>
            <div class="col-7 fs-3 py-4 fw-semibold">Added New MT Options Setting with available MT Engines such as EILMT, AnglaMT & GistMT (NMT) in GoTranslate</div>
         </div>
      </div>
      <div class="carousel-item">
        {% comment %} <img
        width="100%"
        src="{% static './Localisation_App/img/marketing carousel3.png' %}"
        alt=""
      /> {% endcomment %}
      <div class="row text-center">
        <div class="col-4 d-flex-content center">
          <img
            src="{% static './Localisation_App/img/marketing carousel3.png' %}"
            width="200px"
            height="200px"
            alt=""
          />
        </div>
        <div class="col-7 fs-3 py-4 fw-semibold">"GIST Translation System" engine is designed using Deep Learning (Neural Machine Translation) techniques and has been trained on data from generic domains</div>
     </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

Localisation_App/templates/Localisation_App/home/home_mission.html
{% load static %} 
<div class="vision">
    <h3 class="vision-title">{{ ArticleData.2.Article_HeadingName }}</h3>
    <div class="vision-para">{{ ArticleData.2.Article_Description|safe }}</div>
    {% comment %}
    <p class="vision-para">
      and System Integrators by offering Translation services
    </p>
    <p class="vision-para">and tools in regional languages.</p>
    {% endcomment %}
  </div>

Localisation_App/templates/Localisation_App/home/home_success_stories.html
{% load static %} 
<div class="container-fluid">
    <div class="succ-header">
      <span
        ><img
          class="img-fluid"
          style="height: 60px; width: 60px; margin-top: -10px"
          src="{% static './Localisation_App/img/Target.png' %}"
          alt=""
        />Success Stories</span
      >
    </div>
    <div class="succ-subheader">
      Know all our successfull Integration of Localisation services and tools over
      different portals.
    </div>
    <div class="row px-4">
      <div class="col-sm-12 col-lg-6 d-flex justify-content-center">
        <img
          class="img-fluid"
          src="{% static './Localisation_App/img/successStories1.png' %}"
          alt=""
        />
      </div>
      <div class="col-sm-12 col-lg-6">
        <div class="row mx-2 py-2 succ-main-card">
          <div class="col-4">
            <img
              src="{% static './Localisation_App/img/Localization Deployment.png' %}"
              class="succ-img img-fluid"
              alt=""
            />
          </div>
          <div class="col-7 succ-desc mt-2">
            <h2>Localisation Deployment</h2>
            <p>
              Different websites have been integrated with our Language Services
              and Products .
            </p>
            <!-- <div class="succ-link">Know More</div> -->
            <div class="succ-link">
              <a href="{% url 'Localisation_App:successstoryPage' %}"
                ><i
                  class="fa fa-arrow-circle-right"
                  style="font-size: 36px; color: #023047"
                ></i
              ></a>
            </div>
          </div>
        </div>
  
        <div class="row m-2 py-2 succ-main-card">
          <div class="col-7 succ-desc2 mt-2">
            <h2>Proof Of Concept</h2>
            <p>
              Successfully deployed our Indian Language Services and products as
              Proof of Concepts in various organizations.
            </p>
            <div class="succ-link">
              <a href="{% url 'Localisation_App:successstoryPage' %}"
                ><i
                  class="fa fa-arrow-circle-right"
                  style="font-size: 36px; color: #023047"
                ></i
              ></a>
            </div>
          </div>
          <div class="col-1"></div>
          <div class="col-4">
            <img
              src="{% static './Localisation_App/img/Proof of Concept.png' %}"
              class="succ-img img-fluid"
              alt=""
            />
          </div>
        </div>
  
        <div class="row m-2 py-2 succ-main-card">
          <div class="col-4">
            <img
              src="{% static './Localisation_App/img/Portals Translated.png' %}"
              class="succ-img img-fluid"
              alt=""
            />
          </div>
          <div class="col-7 succ-desc3 mt-2">
            <h2>Service Deployment</h2>
            <p>
              Various Organizations are using our Indian Language Services in
              their websites .
            </p>
            <div class="succ-link">
              <a href="{% url 'Localisation_App:successstoryPage' %}"
                ><i
                  class="fa fa-arrow-circle-right"
                  style="font-size: 36px; color: #023047"
                ></i
              ></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>