Localisation_App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


app_name = 'Localisation_App'
urlpatterns = [
     path('', views.Home, name='Home'),
     path('aboutus/', views.aboutus, name='aboutus'),
     path('toolsPage/', views.toolsPage, name='toolsPage'),
     path('tools/', views.tools, name='tools'),
     path('toolsDownloadCounter/<int:id>',
          views.toolsDownloadCounter, name='toolsDownloadCounter'),
     path('toolsReset/', views.toolsReset, name='toolsReset'),
     path('toolsSearch/<tools_title>', views.toolsSearch, name='toolsSearch'),
     path('resourcesPage/', views.resourcesPage, name='resourcesPage'),
     path('resources/', views.resources, name='resources'),
     path('resourceDownloadCounter/<int:id>',
          views.resourceDownloadCounter, name='resourceDownloadCounter'),
     path('resourcesReset/', views.resourcesReset, name='resourcesReset'),
     path('resourceSearch/<slug:resource_title>',
          views.resourceSearch, name='resourceSearch'),
     path('services/', views.services, name='services'),
     path('successstoryPage/', views.successstoryPage, name='successstoryPage'),
     path('successstory/', views.successstory, name='successstory'),
     path('successstorySearch/<story_title>',
          views.successstorySearch, name='successstorySearch'),
     #     path('successstoryReset/', views.successstoryReset, name='successstoryReset'),
     path('submit/', views.submit, name='submit'),
     path('faqs/', views.faqs, name='faqs'),
     path('faqsSearch/<faq_title>', views.faqsSearch, name='faqsSearch'),
     path('contactus/', views.contactus, name='contactus'),
     path('websitepolicy/', views.websitepolicy, name='websitepolicies'),
     path('websitepolicy/<int:id>', views.websitepolicydata,
          name='websitepolicydata'),
     path('termsandcondition/', views.termsandcondition, name='termsandcondition'),
     path('accessibilityStatement/', views.accessibilityStatement,
          name='accessibilityStatement'),
     path('sitemap/', views.sitemap, name='sitemap'),
     path('help/', views.help, name='help'),
     path('submit/<img>', views.submit, name='submit'),
     path('help/<int:id>', views.helpData, name='helpData'),
     path('srvEnableTyping/', views.srvEnableTyping, name='srvEnableTyping'),
     path('srvGoTranslateWebLocalizer/', views.srvGoTranslateWebLocalizer,
          name='srvGoTranslateWebLocalizer'),
     path('srvOnscreenKeyboard/', views.srvOnscreenKeyboard,
          name='srvOnscreenKeyboard'),
     path('srvTTS/', views.srvTTS, name='srvTTS'),
     path('srvTransliteration/', views.srvTransliteration,
          name='srvTransliteration'),
     path('register/', views.Register_user, name="register"),
     path('login/', views.login_user, name='login'),
     path('logout/', views.logout_user, name='logout'),
     path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
     path('changePassword/<token>/', views.changePassword, name='changePassword'),
     path('profile/<int:id>', views.User_Profile, name="profile"),

     path('goTranslate/', views.goTranslate,
          name='goTranslate'),
     path('translation-quote/', views.translation_quote,
          name='translation_quote'),
     path('translation-quote-user-dashboard', views.translation_quote_user_dashboard,
          name='translation_quote_user_dashboard'),
     path('translation-quote-show/<str:application_number>/',
          views.translation_quote_show, name='translation_quote_show'),
     #     path('dashboard2', views.dashboard2, name="dashboard2"),
     path('dashboard', views.dashboard, name="dashboard"),
     path('machine-translation/', views.machine_translation,
          name="machine_translation"),
     path('name-matcher/', views.name_matcher, name="name_matcher"),
     path('empanelled_agencies/', views.empanelled_agencies,
          name="empanelled_agencies"),
     path('bhashini/',views.bhashini,name="bhashini"),
     path('anuvaad/',views.anuvaad, name="anuvaad")

     #     path("Slug_test/<slug:slug>", views.Slug_test, name="Slug_test"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

Localisation_Project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Localisation_App.urls'))

]

Localisation_App/views.py
from threading import currentThread
from wsgiref import validate
from django.db.models import Sum
from django.forms import ValidationError
from Localisation_Project.settings import CACHE_TTL
from .forms import TTSservice, RegisterForm, TranslationQuoteForm, UserLoginForm, UserChangePasswordForm, UserForgetPasswordForm
from django.contrib import messages
from django.core.mail import send_mail, mail_admins
from django.core.paginator import Paginator
from multiprocessing import context
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from .models import *
import random
import requests
from .word_count import crawl_data
from django.contrib.auth.models import User
import uuid
from datetime import date, datetime
from .helpers import send_forget_password_email
import json
from bson import json_util
from django.urls import resolve
import uuid
from django.contrib.auth.decorators import login_required
import logging
from datetime import date
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.core import validators
logger = logging.getLogger('django')
global str_num
global url
CACHE_TTL = getattr(settings,'CACHE_TTL',DEFAULT_TIMEOUT)


# Home Page

def Home(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("url", url)
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_Article_data"):
            articleData = cache.get("All_Article_data")
            print("cache data")
        else:
            articleData = Article.objects.all()
            cache.set("All_Article_data", articleData)
            print("database data")

        if cache.get("All_SuccessStories_data"):
            successStoriesData = cache.get("All_SuccessStories_data")
            print("cache data")
        else:
            successStoriesData = SuccessStories.objects.all()
            cache.set("All_SuccessStories_data", successStoriesData)
            print("database data")

        if cache.get("All_Services_data"):
            servicesdata = cache.get("All_Services_data")
            print("cache data")
        else:
            servicesdata = Services.objects.all()
            cache.set("All_Services_data", servicesdata)
            print("database data")

        if cache.get("All_NewsAndEvents_data"):
            newsAndEventsData = cache.get("All_NewsAndEvents_data")
            print("cache data")
        else:
            newsAndEventsData = NewsAndEvents.objects.all()
            cache.set("All_NewsAndEvents_data", newsAndEventsData)
            print("database data")
        logger.info("Home page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
            'SuccessStoriesData': successStoriesData,
            'NewsAndEventsData': newsAndEventsData,
            'Servicesdata': servicesdata
        }
        return render(request, 'Localisation_App/home.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")



# About Us Page

def aboutus(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        print("hello")
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")
        if cache.get("All_About_data"):
            articleData = cache.get("All_About_data")
            print("cache data")
        else:
            articleData = Article.objects.all().filter(Article_HeadingName="About Us")
            cache.set("All_About_data", articleData)
            print("database data")
        logger.info("About Us page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
        }
        return render(request, 'Localisation_App/aboutus.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")

# Tools Page

def toolsPage(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data"):
            tools_Data=cache.get("All_ToolsData_data")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data",tools_Data)
            print("database data")
        Tools_Category.objects.all().update(Tools_Cat_Status=False)
        if cache.get("All_ToolsCategory_data"):
            toolsCategory_data=cache.get("All_ToolsCategory_data")
            print("cache data")
        else:
            toolsCategory_data = Tools_Category.objects.all()
            cache.set("All_ToolsCategory_data",toolsCategory_data)
            print("database data")
        count = ToolsData.objects.all().count()
        page = Paginator(tools_Data, 8)
        page_list = request.GET.get('page')
        page = page.get_page(page_list)
        count = tools_Data.count()
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'toolsdata': tools_Data,
            'tools_title': 'none',
            'toolscategory': toolsCategory_data,
            "page": page,
            'status_All_Checked': 'True',
            'Pagination_Type': 'All_Data',
            'count': count,
            'form': UserLoginForm()
        }
        logger.info("Tools page getting displayed")
        # if request.user.is_authenticated:
        #     return render(request, 'Localisation_App/tools.html', context)
        # else:
        return render(request, 'Localisation_App/tools.html', context)
    except:
        return render(request, "Localisation_App/serverdown.html")


def tools(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        checklist1 = []
        category_name = []
        pagestatus = False
        filtered_Tools_Data = ToolsData.objects.none()
        if cache.get("All_top_menu_items_data_data"):
            top_menu_items_data = cache.get("All_top_menu_items_data_data")
            print("cache data")
        else:
            top_menu_items_data = TopMenuItems.objects.all()
            cache.set("All_top_menu_items_data_data", top_menu_items_data)
            print("database data")

        if cache.get("All_footer_menu_items_data_data"):
            footer_menu_items_data = cache.get("All_footer_menu_items_data_data")
            print("cache data")
        else:
            footer_menu_items_data = FooterMenuItems.objects.all()
            cache.set("All_footer_menu_items_data_data", footer_menu_items_data)
            print("database data")

        if cache.get("All_ToolsData_data1"):
            tools_Data=cache.get("All_ToolsData_data1")
            print("cache data")
        else:
            tools_Data = ToolsData.objects.all()
            cache.set("All_ToolsData_data1",tools_Data)
            print("database data")
        
        toolsCategory_data = Tools_Category.objects.all()
        
        count = ToolsData.objects.all().count()

        if request.method == "POST":
            if request.POST.get('all_checkbox') != 'all_Checked':
                category_name = []
                filtered_Tools_Data = ToolsData.objects.none()
                print("dumydata", filtered_Tools_Data)
                checklist = request.POST.getlist('checkbox')
                Tools_Category.objects.all().update(Tools_Cat_Status=False)
                try:
                    for cat_check in checklist:
                        Tools_Category.objects.filter(

Localisation_App/templates/Localisation_App/footer_links/accessibility_statement.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Accessibility Statements{% endblock %}
{% load static %} 
{% block accessibilitystatement %}

<!-- <title>Accessibility statement</title> -->

<link
  href="{% static 'Localisation_App/css/footer_links/accessibility_statement.css' %}"
  rel="stylesheet"
/>
<div class="access-main">
<div class="container main-container">
  <div class="text-center p-3">
    <input
      type="button"
      class="text-center rounded-5 px-5 access-heading"
      value="{{ content.Footer_Links_Title }}"
      disabled
    />
  </div>
  <!-- <h4 class="as-main-title">{{ content.Footer_Links_Title }}</h4> -->
  <div class="access-content">

    {{ content.Footer_Links_Content|safe }}
 
    
  </div>
 
</div>
</div>

{% endblock %}

Localisation_App/templates/Localisation_App/footer_links/empanelled_agencies.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Empanelled Agencies{% endblock %}
{% load static %}
 
{% block empanelled_agencies %}

<link
  href="{% static 'Localisation_App/css/footer_links/empanelled_agencies.css' %}"
  rel="stylesheet"
/>

  <div class="container">
    <div class="text-center p-3">
      <input type="text" class="text-center rounded-5 emp_agencies-heading" value="Empanelled Agencies" disabled />
    </div>
    <div class="mt-4">

      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th scope="col">Sr. No.</th>
            <th scope="col">Company Name</th>
            <th scope="col">Contact Person</th>
            <th scope="col">E-Mail Address</th>
          </tr>
        </thead>
        <tbody class="table-body">
          {% if empanelled_agencies_data %}
        
          {% for e_data in empanelled_agencies_data %}
          <tr>
            <th class='px-3 ' >{{forloop.counter}}</th>
            <td>{{e_data.company_name}}</td>
            <td>{{e_data.contact_person}}</td>
            <td>
              {% for data in e_data.email %}
              {{data}}
              <br />{% endfor %}
            </td>
          </tr>
          {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
    </div>
    
    
    {% endblock %}

Localisation_App/templates/Localisation_App/footer_links/help.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Help{% endblock %}
{% load static %}
{% block help %}

<link href="{% static 'Localisation_App/css/footer_links/help.css' %}" rel="stylesheet" />
<div class="help-main">
<div class="container-fluid main-container">
  <div class="text-center p-3">
    <input
      type="button"
      class="text-center rounded-5 px-5 help-heading"
      value="Help"
      disabled
    />
  </div>
  <div class="row main">
    <div class="col-3 first-section" >
      <nav class="help-navigation">
        <ul>
          
          {% for f_sub_data in footer_sub_data %}
          <li class="nav-item">
            <a  href="{% url 'Localisation_App:helpData' f_sub_data.id %}">{{f_sub_data.Footer_Links_Info_SubTitle}}</a>
          </li>
          {% endfor %}
        </ul>
      </nav>
    </div>
    <div class="col-8 second-section"  style="background-color: #F2F2F2;">
      <!-- Sections of this Portal start from here -->

      


      {% if content %}
      <div id="sec1">
        <h4 class="help-title" >{{ content.Footer_Links_Info_SubTitle }}</h4>

        <div style="font-size: 20px;" > {{ content.Footer_Links_Info_SubContent|safe }}</div>
      </div>
      {% else %}
      <h1>No data found!</h1>
      {% endif %}

      <!-- Software to open zip files ends here -->
    </div>
  </div>
</div>
</div>
{% endblock%}

Localisation_App/templates/Localisation_App/footer_links/sitemap.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Sitemap{% endblock %}
{% load static %}

{% block sitemap %}

<link
  href="{% static 'Localisation_App/css/footer_links/sitemap.css' %}"
  rel="stylesheet"
/>
<div class="site-main">

<div class="container main-container">
  <div class="text-center p-3">
    <input
      type="button"
      class="text-center rounded-5 px-5 sitemap-heading"
      value="{{ content.Footer_Links_Title }}"
      disabled
    />
  </div>
  <!-- <h4 class="sitemap-main-title">{{ content.Footer_Links_Title }}</h4> -->
  
   <div> {{ content.Footer_Links_Content|safe }}</div>
</div>
  
</div>
{% endblock %}

Localisation_App/templates/Localisation_App/footer_links/websitepolicies.html
{% extends 'Localisation_App/base.html' %}
{% block title %}Website policies{% endblock %}
 {% load static %} {% block websitepolicies %}


<div class="Web-main">
<link
  href="{% static 'Localisation_App/css/footer_links/websitepolicies.css' %}"
  rel="stylesheet"
/>

<div class="container-fluid main-container">
  <!-- <h4 class="web-main-title">Website Policies</h4> -->
  <div class="text-center p-3">
    <input
      type="button"
      class="text-center rounded-5 px-5 webpolicies-heading"
      value="Website Policies"
      disabled
    />
  </div>

  <div class="row main">
    <div class="col-2 first-section">
      <nav class="navigation">
        <ul>
          {% for f_sub_data in footer_sub_data %}
          <li class="nav-item">
            <a
              href="{% url 'Localisation_App:websitepolicydata' f_sub_data.id %}"
              id="an1"
              onclick="changecolor(id)"
              class="active"

              >{{f_sub_data.Footer_Links_Info_SubTitle}}</a
            >
          </li>
          
          {% endfor %}
        </ul>
      </nav>
    </div>
    <div class="col-9 second-section">
      {% if content %}
      <section id="#copyright">
        <div>
          <h4 class="web-title">{{ content.Footer_Links_Info_SubTitle }}</h4>
          <div class="web-content">
            {{ content.Footer_Links_Info_SubContent|safe }}
          </div>
        </div>
      </section>
      {% else %}
      <h1>No data found!</h1>
      {% endif %}

      {% comment %} <section id="policy">
        <div>
          <h4 class="web-title">Hyperlinking Policy</h4>
          <h5 class="web-sub-title">Links to external websites/portals</h5>
          <p class="web-content">
            In some places in this portal, you shall find links to other
            websites/portals.These links have been placed for your convenience.
            C-DAC is not responsible for the contents and reliability of the
            linked websites and does not necessarily endorse the views expressed
            in them. Mere presence of the link or its listing on this portal
            should not be assumed as endorsement of any kind. We can not
            guarantee that these links will work all times and we have no
            control over availability of linked pages.
          </p>
          <h5 class="web-sub-title">
            Links to localization portal by other websites
          </h5>
          <p class="web-content">
            We do not object to you linking directly to the information that is
            hosted on this portal and no prior permission is required for the
            same. However, we would like you to inform us about any links
            provided to this portal so that you can be informed of any changes
            or updates therein. Also, we do not permit our pages to be loaded
            into frames on your site. The pages belonging to this portal must
            load into a newly opened browser window of the user.
          </p>
        </div>
      </section>
      <section id="terms">
        <div>
          <h4 class="web-title">Terms of Use</h4>
          <p class="web-content">
            This portal is designed, developed and hosted by C-DAC., Though all
            efforts have been made to ensure the accuracy and currency of the
            content on this pPortal, the same should not be construed as a
            statement of law or used for any legal purposes. C-DAC accepts no
            responsibility in relation to the accuracy, completeness, usefulness
            or otherwise, of the contents. Users are advised to verify/check any
            information with the relevant Government department(s) and/or other
            source(s), and to obtain any appropriate professional advice before
            acting on the information provided in the portal.
          </p>
          <p>
            In no event will the Government of India or C-DAC be liable for any
            expense, loss or damage including, without limitation, indirect or
            consequential loss or damage, or any expense, loss or damage
            whatsoever arising from use, or loss of data, arising out of, or in
            connection with the use of this portal.
          </p>
          <p>
            Links to other websites that have been included on this portal are
            provided for public convenience only. C-DAC is not responsible for
            the contents or reliability of linked websites and does not endorse
            the view expressed within them. We cannot guarantee the availability
            of such linked pages at all times.
          </p>
          <p>
            These terms and conditions shall be governed by, and construed in
            accordance with the Indian Laws. Any dispute arising under these
            terms and conditions shall be subject to the exclusive jurisdiction
            of the courts of India.
          </p>
        </div>
      </section>

      <section id="privacy">
        <div>
          <h4 class="web-title">Privacy Policy</h4>
          <p class="web-content">
            Localization Portal and applications based on localization portal
            does not automatically capture any specific personal information
            from you, (like name, phone number or e-mail address), that allows
            us to identify you individually.
          </p>
          <p>
            If for any specific reason, the localization portal requests you to
            provide personal information, you will be informed for the
            particular purposes for which the information is gathered and
            adequate security measures will be taken to protect your personal
            information.
          </p>
          <p>
            We do not sell or share any personally identifiable information
            volunteered on the localization portal site to any third party
            (public/private). Any information provided to this Portal portal
            will be protected from loss, misuse, unauthorized access or
            disclosure, alteration, or destruction.
          </p>
          <p>
            We gather certain information about the user, such as Internet
            Protocol (IP) addresses, domain name, browser type, operating
            system, the date and time of the visit and the pages visited. We
            make no attempt to link these addresses with the identity of
            individuals visiting our site unless an attempt to damage the site
            has been detected.
          </p>
        </div>
      </section> {% endcomment %}
    </div>
  </div>
</div>

{% comment %}
<script>
  function changecolor(id) {
    console.log(id);
    let tag1 = document.getElementById(id);
    tag1.setAttribute("style", "color:yellow");
  }
</script>
{% endcomment %} 
</div>

{% endblock %}